In [1]:
pwd

'd:\\GitHub\\JOB-BSP\\notebooks\\augmentations'

In [2]:
# AEDA: An Easier Data Augmentation Technique for Text classification
# Akbar Karimi, Leonardo Rossi, Andrea Prati

import random

random.seed(0)

PUNCTUATIONS = ['.', ',', '!', '?', ';', ':']
NUM_AUGS = [1, 2, 4, 8]
PUNC_RATIO = 0.3

# Insert punction words into a given sentence with the given ratio "punc_ratio"
def insert_punctuation_marks(sentence, punc_ratio=PUNC_RATIO):
	words = sentence.split(' ')
	new_line = []
	q = random.randint(1, int(punc_ratio * len(words) + 1))
	qs = random.sample(range(0, len(words)), q)

	for j, word in enumerate(words):
		if j in qs:
			new_line.append(PUNCTUATIONS[random.randint(0, len(PUNCTUATIONS)-1)])
			new_line.append(word)
		else:
			new_line.append(word)
	new_line = ' '.join(new_line)
	return new_line


def main():
	for aug in NUM_AUGS:
		data_aug = []
		with open(r'../../datasets/eda_aug/train_eda_preparation.txt', 'r') as train_orig:
			for line in train_orig:
				line1 = line.split('\t')
				label = line1[0]
				sentence = line1[1]
				for i in range(aug):
					sentence_aug = insert_punctuation_marks(sentence)
					line_aug = '\t'.join([label, sentence_aug])
					data_aug.append(line_aug)
				data_aug.append(line)

		with open(r'../../datasets/aeda_aug/train_aeda_processed.txt', 'w') as train_orig_plus_augs:
			train_orig_plus_augs.writelines(data_aug)


if __name__ == "__main__":
	# for dataset in DATASETS:
    main()

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv(r"../../datasets/aeda_aug/train_aeda_processed.txt", sep='\t', header=None)
df.columns = ["priority", "text"]
df = df[["text", "priority"]]
df

                                                    text priority
0      Detect uncaught exceptions in UoWProcessor to ...    Major
1      Detect uncaught exceptions in UoWProcessor to ...    Major
2      Detect uncaught exceptions in UoWProcessor to ...    Major
3      Detect uncaught exceptions in UoWProcessor to ...    Major
4      Detect uncaught exceptions in UoWProcessor to ...    Major
...                                                  ...      ...
28777  Sending to http , endpoint may , double encodi...    Major
28778  Sending to http endpoint may double encoding p...    Major
28779  Sending to http endpoint may double encoding p...    Major
28780  Sending to http endpoint may double encoding p...    Major
28781  Sending to http endpoint may double encoding p...    Major

[28782 rows x 2 columns]

In [6]:
df["priority"].value_counts()

priority
Major       18702
Minor        7218
Trivial      1323
Critical     1188
Blocker       351
Name: count, dtype: int64

In [7]:
df[df.duplicated(subset=["priority", "text"], keep='first')]["priority"].value_counts()

priority
Major       17
Minor        7
Trivial      2
Critical     1
Name: count, dtype: int64

In [8]:
df.drop_duplicates(subset=["priority", "text"], inplace=True)
df = df.reset_index(drop=True)
df

                                                    text priority
0      Detect uncaught exceptions in UoWProcessor to ...    Major
1      Detect uncaught exceptions in UoWProcessor to ...    Major
2      Detect uncaught exceptions in UoWProcessor to ...    Major
3      Detect uncaught exceptions in UoWProcessor to ...    Major
4      Detect uncaught exceptions in UoWProcessor to ...    Major
...                                                  ...      ...
28750  Sending to http , endpoint may , double encodi...    Major
28751  Sending to http endpoint may double encoding p...    Major
28752  Sending to http endpoint may double encoding p...    Major
28753  Sending to http endpoint may double encoding p...    Major
28754  Sending to http endpoint may double encoding p...    Major

[28755 rows x 2 columns]

In [9]:
df["priority"].value_counts()

priority
Major       18685
Minor        7211
Trivial      1321
Critical     1187
Blocker       351
Name: count, dtype: int64

In [10]:
df.to_csv(r"../../datasets/aeda_aug/train_aeda.csv", index=None, encoding="utf-8-sig")